package com.student.studentmanagement.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;

/**
 * Entity class representing the 'Student' table in the database.
 * Includes validation annotations and is managed by JPA/Hibernate.
 */
@Entity // Marks this class as a JPA entity
@Data // Lombok: generates getters, setters, toString, equals, and hashCode
@NoArgsConstructor // Lombok: generates no-args constructor
@AllArgsConstructor // Lombok: generates constructor with all fields
public class Student {

    /**
     * Primary key of the Student table.
     * Automatically generated by the database using IDENTITY strategy.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Name of the student.
     * Must not be blank (not null and not just whitespace).
     */
    @NotBlank(message = "Name cannot be empty")
    private String name;

    /**
     * Age of the student.
     * Must be a positive number (minimum value 1).
     */
    @Min(value = 1, message = "Age must be positive")
    private int age;

    /**
     * Grade achieved by the student.
     * Must match one of the allowed values: A+, A, B+, B, C+, C, D, or F.
     */
    @Pattern(regexp = "^(A\\+|A|B\\+|B|C\\+|C|D|F)$", message = "Invalid grade format")
    private String grade;

    /**
     * Address of the student (optional).
     */
    private String address;
}
